# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ben Hymers
tagline:          "Ben Hymers' website"
description:      'Video game software engineer at Creative Assembly, previously at Rare.'
url:              http://hymerman.github.io
baseurl:          /

author:
  name:           'Ben Hymers'
  url:            http://www.benhymers.com

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/hymerman/hymerman.github.io
