# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ben Hymers
tagline:          "Ben Hymers' website"
description:      'Video game software engineer at Creative Assembly, previously at Rare.'
url:              http://hymerman.github.io
baseurl:          /

author:
  name:           'Ben Hymers'
  url:            http://www.benhymers.com

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/hymerman/hymerman.github.io

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://hymerman.github.io


# Your disqus shortname, entering this will enable commenting on posts
disqus: benhymers

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-1548272-4

# Use the following plug-ins
gems:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE.md
    - README.md
